<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>Yuzuha.SetupBridge</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <ApplicationIcon>../assets/yuzuha.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Newtonsoft.Json"><HintPath>../../src/lib/net35/Newtonsoft.Json.dll</HintPath></Reference>
  </ItemGroup>
</Project>
