; Project-authored Simplified Chinese overrides; uncommon system messages fall back to Inno English.
[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=0
DialogFontName=Microsoft YaHei UI
DialogFontSize=9

[Messages]
SetupAppTitle=安装
SetupWindowTitle=安装 - %1
UninstallAppTitle=卸载
UninstallAppFullTitle=%1 卸载
InformationTitle=信息
ConfirmTitle=确认
ErrorTitle=错误
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonNo=否(&N)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&B)…
ButtonWizardBrowse=浏览(&R)…
SelectLanguageTitle=选择安装语言 / Setup language
SelectLanguageLabel=请选择安装时使用的语言。
ClickNext=点击“下一步”继续，或点击“取消”退出。
BrowseDialogTitle=选择文件夹
BrowseDialogLabel=选择一个文件夹，然后点击“确定”。
WizardLicense=许可协议
LicenseLabel=继续之前请阅读以下内容。
LicenseLabel3=请阅读许可协议。继续安装前需要接受协议条款。
LicenseAccepted=我接受协议(&A)
LicenseNotAccepted=我不接受协议(&D)
WizardSelectDir=选择安装目录
SelectDirDesc=将 [name] 安装到哪里？
SelectDirLabel3=程序将安装到以下目录。
SelectDirBrowseLabel=点击“下一步”继续，或点击“浏览”选择其他目录。
DiskSpaceMBLabel=至少需要 [mb] MB 可用空间。
DirExistsTitle=目录已存在
DirExists=目录：%n%n%1%n%n已经存在。是否使用此目录？安装器仍会检查管理标记。
DirDoesntExistTitle=目录不存在
DirDoesntExist=目录：%n%n%1%n%n不存在。是否创建？
WizardReady=准备安装
ReadyLabel1=安装计划已预览。点击“安装”执行，点击“上一步”修改选择。
ReadyLabel2a=点击“安装”开始，或点击“上一步”检查设置。
ReadyMemoDir=安装目录：
WizardPreparing=准备安装
PreparingDesc=核对批准计划与当前文件状态。
WizardInstalling=正在安装
InstallingLabel=正在执行批准的安装计划，请稍候。
StatusExtractFiles=正在复制文件…
StatusCreateIcons=正在创建快捷方式…
StatusRunProgram=正在应用配置…
ExitSetupTitle=退出安装
ExitSetupMessage=安装尚未完成。现在退出将不再继续安装。%n%n是否退出？
ConfirmUninstall=确认卸载 %1？%n%n受管理的外部配置将恢复安装前内容；发生冲突时会停止。用户数据保留。
UninstallStatusLabel=正在卸载 %1，请稍候。
UninstalledAll=%1 已卸载。用户数据和安装报告仍保留。
ErrorCreatingDir=无法创建目录“%1”
InvalidPath=请输入包含盘符的完整本机路径。
InvalidDirName=目录名称无效。
SetupAlreadyRunning=安装器已经在运行。
